### PR TITLE
Created injectSearch method into SearchBarController

### PR DESCRIPTION
**Pull request by MohamedEL-Torky**
Anyone can now inject search text into the search bar using the SearchBarController you provided by adding new method injectSearch that accepts a search text and a search Function for greater modifiability.

Use Cases:
---------------
Devs now can add buttons into the placeholder screen for search shortcuts or even add a QR / Barcode reader buttons that obviously read QR / Bar codes and inject the scanned values into the search field to automatically search after the user acquire the data from the reader.

### CODE REVIEW

**Comment by joaovvrodrigues** [comment]
I really need this feature in my project, how can I add it?

**Comment by MohamedEL-Torky** [comment]
Hi, thanks for reaching out.

First, you will need to add this line to your pubspec.yaml

>
> flappy_search_bar:
>     git:
>       url: https://github.com/MohamedEL-Torky/flappy_search_bar


and remove flappy_search_bar from it, because it will conflict with my
edited package. You can switch back to the flappy_search_bar package once
he accepted my pull request.


Secondly, you will need to declare searchBarController inside your widget
class.

>SearchBarController<DataType> searchBarController =
>       new SearchBarController();
>

Then add it to the SearchBar widget like that

>SearchBar<ProductData>(
>
>            .....
>
>           searchBarController: searchBarController,
>
>            ....
>
>),


Finally, you will now be able to use the searchBarController injectSearch
method like that

searchBarController.injectSearch(searchString, searchFunction);


The search string parameter is what the search function will search for.
The search function is just like the function you feed to SearchBar widget
or you can customize another one in case you need to apply another search
method for that case.

**Review by ThomasEcalle — APPROVED** [review]
Hi @MohamedEL-Torky 

First of all, I am sorry for the delay.
The situation in my company (in France) with the Covid-19 has forced us to put our open source projects on the side for a moment... But I am back ! :)

I thank you a lot for your work !
I find your idea really elegant and nice :)
I'll add it to the next version with pleasure

Thanks a lot for your work  !
I'll try to be more present on this package, despite the difficult context that had lead us to change a lot the way we work here :)

**Comment by MohamedEL-Torky** [comment]
Hey @ThomasEcalle.
No need to be sorry I understand the current situation. The most important thing is that you're fine. I would like to thank you for your efforts making this package which is was really great help for me and many other developers out there, and don't try to push yourself too hard we are here for you to help make this package even better that's the power of open source.

Remeber stay safe and work from home <3

**Comment by rohan3usturge** [comment]
Hi @MohamedEL-Torky 

Has this fix been released as a package ? I don't see this in the latest version.

**Comment by MohamedEL-Torky** [comment]
Hey @rohan3usturge 
sorry for the late reply. I have checked the package on pub dev but unfortunately, it seems quite outdated.
If you're still looking for using this feature I welcome you to use my fork by writing the following on your pubspec.yaml file.

```
flappy_search_bar:
     git:
       url: https://github.com/MohamedEL-Torky/flappy_search_bar
```

**Pull request merged**
